/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type CreateScheduleRequestBody = {
    data: components.ScheduleCreate;
};

export type CreateScheduleRequest = {
    filter?: string | undefined;
    requestBody?: CreateScheduleRequestBody | undefined;
};

/**
 * Success. The schedule is created.
 */
export type CreateScheduleResponseBody = {
    data?: components.Schedule | undefined;
};

export type CreateScheduleResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. The schedule is created.
     */
    object?: CreateScheduleResponseBody | undefined;
};

/** @internal */
export namespace CreateScheduleRequestBody$ {
    export type Inbound = {
        data: components.ScheduleCreate$.Inbound;
    };

    export const inboundSchema: z.ZodType<CreateScheduleRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.ScheduleCreate$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: components.ScheduleCreate$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateScheduleRequestBody> = z
        .object({
            data: components.ScheduleCreate$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace CreateScheduleRequest$ {
    export type Inbound = {
        filter?: string | undefined;
        RequestBody?: CreateScheduleRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateScheduleRequest, z.ZodTypeDef, Inbound> = z
        .object({
            filter: z.string().optional(),
            RequestBody: z.lazy(() => CreateScheduleRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        filter?: string | undefined;
        RequestBody?: CreateScheduleRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateScheduleRequest> = z
        .object({
            filter: z.string().optional(),
            requestBody: z.lazy(() => CreateScheduleRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace CreateScheduleResponseBody$ {
    export type Inbound = {
        data?: components.Schedule$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateScheduleResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Schedule$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Schedule$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateScheduleResponseBody> = z
        .object({
            data: components.Schedule$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });
}

/** @internal */
export namespace CreateScheduleResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: CreateScheduleResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateScheduleResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => CreateScheduleResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: CreateScheduleResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateScheduleResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => CreateScheduleResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
