/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type CreateSubscriptionRequestBody = {
    data: components.BuildSubscription;
};

export type CreateSubscriptionRequest = {
    filter?: string | undefined;
    requestBody?: CreateSubscriptionRequestBody | undefined;
};

/**
 * Success. The subscription is created.
 */
export type CreateSubscriptionResponseBody = {
    data?: components.Subscription | undefined;
};

export type CreateSubscriptionResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. The subscription is created.
     */
    object?: CreateSubscriptionResponseBody | undefined;
};

/** @internal */
export namespace CreateSubscriptionRequestBody$ {
    export type Inbound = {
        data: components.BuildSubscription$.Inbound;
    };

    export const inboundSchema: z.ZodType<CreateSubscriptionRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.BuildSubscription$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: components.BuildSubscription$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriptionRequestBody> =
        z
            .object({
                data: components.BuildSubscription$.outboundSchema,
            })
            .transform((v) => {
                return {
                    data: v.data,
                };
            });
}

/** @internal */
export namespace CreateSubscriptionRequest$ {
    export type Inbound = {
        filter?: string | undefined;
        RequestBody?: CreateSubscriptionRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriptionRequest, z.ZodTypeDef, Inbound> = z
        .object({
            filter: z.string().optional(),
            RequestBody: z.lazy(() => CreateSubscriptionRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        filter?: string | undefined;
        RequestBody?: CreateSubscriptionRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriptionRequest> = z
        .object({
            filter: z.string().optional(),
            requestBody: z.lazy(() => CreateSubscriptionRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace CreateSubscriptionResponseBody$ {
    export type Inbound = {
        data?: components.Subscription$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriptionResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Subscription$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Subscription$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriptionResponseBody> =
        z
            .object({
                data: components.Subscription$.outboundSchema.optional(),
            })
            .transform((v) => {
                return {
                    ...(v.data === undefined ? null : { data: v.data }),
                };
            });
}

/** @internal */
export namespace CreateSubscriptionResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: CreateSubscriptionResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriptionResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => CreateSubscriptionResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: CreateSubscriptionResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriptionResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => CreateSubscriptionResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
