/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type CreateSubscriberRequestBody = {
    data: components.SubscriberCreate;
};

export type CreateSubscriberRequest = {
    filter?: string | undefined;
    requestBody?: CreateSubscriberRequestBody | undefined;
};

/**
 * Success. The subscriber is created.
 */
export type CreateSubscriberResponseBody = {
    data?: components.Subscriber | undefined;
};

export type CreateSubscriberResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. The subscriber is created.
     */
    object?: CreateSubscriberResponseBody | undefined;
};

/** @internal */
export namespace CreateSubscriberRequestBody$ {
    export type Inbound = {
        data: components.SubscriberCreate$.Inbound;
    };

    export const inboundSchema: z.ZodType<CreateSubscriberRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.SubscriberCreate$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: components.SubscriberCreate$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriberRequestBody> = z
        .object({
            data: components.SubscriberCreate$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace CreateSubscriberRequest$ {
    export type Inbound = {
        filter?: string | undefined;
        RequestBody?: CreateSubscriberRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriberRequest, z.ZodTypeDef, Inbound> = z
        .object({
            filter: z.string().optional(),
            RequestBody: z.lazy(() => CreateSubscriberRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        filter?: string | undefined;
        RequestBody?: CreateSubscriberRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriberRequest> = z
        .object({
            filter: z.string().optional(),
            requestBody: z.lazy(() => CreateSubscriberRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.filter === undefined ? null : { filter: v.filter }),
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace CreateSubscriberResponseBody$ {
    export type Inbound = {
        data?: components.Subscriber$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriberResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Subscriber$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Subscriber$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriberResponseBody> = z
        .object({
            data: components.Subscriber$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });
}

/** @internal */
export namespace CreateSubscriberResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: CreateSubscriberResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateSubscriberResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => CreateSubscriberResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: CreateSubscriberResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateSubscriberResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => CreateSubscriberResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
