/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type DeleteScheduleRequest = {
    /**
     * The unique identifier of the schedule.
     */
    scheduleUuid: string;
};

export type DeleteScheduleResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteScheduleRequest$ {
    export type Inbound = {
        schedule_uuid: string;
    };

    export const inboundSchema: z.ZodType<DeleteScheduleRequest, z.ZodTypeDef, Inbound> = z
        .object({
            schedule_uuid: z.string(),
        })
        .transform((v) => {
            return {
                scheduleUuid: v.schedule_uuid,
            };
        });

    export type Outbound = {
        schedule_uuid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteScheduleRequest> = z
        .object({
            scheduleUuid: z.string(),
        })
        .transform((v) => {
            return {
                schedule_uuid: v.scheduleUuid,
            };
        });
}

/** @internal */
export namespace DeleteScheduleResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<DeleteScheduleResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteScheduleResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
