/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type DeleteOfferingRequest = {
    /**
     * The unique identifier of the offering.
     */
    offeringUuid: string;
};

export type DeleteOfferingResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteOfferingRequest$ {
    export type Inbound = {
        offering_uuid: string;
    };

    export const inboundSchema: z.ZodType<DeleteOfferingRequest, z.ZodTypeDef, Inbound> = z
        .object({
            offering_uuid: z.string(),
        })
        .transform((v) => {
            return {
                offeringUuid: v.offering_uuid,
            };
        });

    export type Outbound = {
        offering_uuid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteOfferingRequest> = z
        .object({
            offeringUuid: z.string(),
        })
        .transform((v) => {
            return {
                offering_uuid: v.offeringUuid,
            };
        });
}

/** @internal */
export namespace DeleteOfferingResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<DeleteOfferingResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteOfferingResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
