/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type GetPlanRequest = {
    /**
     * The unique identifier of the plan.
     */
    planUuid: string;
};

/**
 * Success. The details of the plan are returned.
 */
export type GetPlanResponseBody = {
    data?: components.Plan | undefined;
};

export type GetPlanResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. The details of the plan are returned.
     */
    object?: GetPlanResponseBody | undefined;
};

/** @internal */
export namespace GetPlanRequest$ {
    export type Inbound = {
        plan_uuid: string;
    };

    export const inboundSchema: z.ZodType<GetPlanRequest, z.ZodTypeDef, Inbound> = z
        .object({
            plan_uuid: z.string(),
        })
        .transform((v) => {
            return {
                planUuid: v.plan_uuid,
            };
        });

    export type Outbound = {
        plan_uuid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPlanRequest> = z
        .object({
            planUuid: z.string(),
        })
        .transform((v) => {
            return {
                plan_uuid: v.planUuid,
            };
        });
}

/** @internal */
export namespace GetPlanResponseBody$ {
    export type Inbound = {
        data?: components.Plan$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetPlanResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Plan$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Plan$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPlanResponseBody> = z
        .object({
            data: components.Plan$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });
}

/** @internal */
export namespace GetPlanResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GetPlanResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetPlanResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetPlanResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GetPlanResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPlanResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetPlanResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
