/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type GetScheduleRequest = {
    /**
     * The unique identifier of the schedule.
     */
    scheduleUuid: string;
};

/**
 * Success. A schedule is returned.
 */
export type GetScheduleResponseBody = {
    data?: components.Schedule | undefined;
};

export type GetScheduleResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. A schedule is returned.
     */
    object?: GetScheduleResponseBody | undefined;
};

/** @internal */
export namespace GetScheduleRequest$ {
    export type Inbound = {
        schedule_uuid: string;
    };

    export const inboundSchema: z.ZodType<GetScheduleRequest, z.ZodTypeDef, Inbound> = z
        .object({
            schedule_uuid: z.string(),
        })
        .transform((v) => {
            return {
                scheduleUuid: v.schedule_uuid,
            };
        });

    export type Outbound = {
        schedule_uuid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetScheduleRequest> = z
        .object({
            scheduleUuid: z.string(),
        })
        .transform((v) => {
            return {
                schedule_uuid: v.scheduleUuid,
            };
        });
}

/** @internal */
export namespace GetScheduleResponseBody$ {
    export type Inbound = {
        data?: components.Schedule$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetScheduleResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Schedule$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Schedule$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetScheduleResponseBody> = z
        .object({
            data: components.Schedule$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });
}

/** @internal */
export namespace GetScheduleResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GetScheduleResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetScheduleResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetScheduleResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GetScheduleResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetScheduleResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetScheduleResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
