/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type ListPlansRequest = {
    /**
     * The current offset by number of records, not pages. Offset is zero-based. The maximum records you can offset is 10,000. If no page size is set, the [page length](https://elasticpath.dev/docs/commerce-cloud/global-project-settings/settings-overview#page-length) store setting is used.
     */
    pageOffset?: number | undefined;
    /**
     * The maximum number of records per page for this response. You can set this value up to 100. If no page size is set, the [page length](https://elasticpath.dev/docs/commerce-cloud/global-project-settings/settings-overview#page-length) store setting is used.
     */
    pageLimit?: number | undefined;
};

/**
 * Success. A list of subscription plans is returned.
 */
export type ListPlansResponseBody = {
    data?: Array<components.Plan> | undefined;
    links?: Record<string, components.Link> | undefined;
};

export type ListPlansResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. A list of subscription plans is returned.
     */
    object?: ListPlansResponseBody | undefined;
};

/** @internal */
export namespace ListPlansRequest$ {
    export type Inbound = {
        "page[offset]"?: number | undefined;
        "page[limit]"?: number | undefined;
    };

    export const inboundSchema: z.ZodType<ListPlansRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "page[offset]": z.number().int().optional(),
            "page[limit]": z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v["page[offset]"] === undefined ? null : { pageOffset: v["page[offset]"] }),
                ...(v["page[limit]"] === undefined ? null : { pageLimit: v["page[limit]"] }),
            };
        });

    export type Outbound = {
        "page[offset]"?: number | undefined;
        "page[limit]"?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlansRequest> = z
        .object({
            pageOffset: z.number().int().optional(),
            pageLimit: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.pageOffset === undefined ? null : { "page[offset]": v.pageOffset }),
                ...(v.pageLimit === undefined ? null : { "page[limit]": v.pageLimit }),
            };
        });
}

/** @internal */
export namespace ListPlansResponseBody$ {
    export type Inbound = {
        data?: Array<components.Plan$.Inbound> | undefined;
        links?: Record<string, components.Link$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ListPlansResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(components.Plan$.inboundSchema).optional(),
            links: z.record(components.Link$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
                ...(v.links === undefined ? null : { links: v.links }),
            };
        });

    export type Outbound = {
        data?: Array<components.Plan$.Outbound> | undefined;
        links?: Record<string, components.Link$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlansResponseBody> = z
        .object({
            data: z.array(components.Plan$.outboundSchema).optional(),
            links: z.record(components.Link$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
                ...(v.links === undefined ? null : { links: v.links }),
            };
        });
}

/** @internal */
export namespace ListPlansResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: ListPlansResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ListPlansResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => ListPlansResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: ListPlansResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlansResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => ListPlansResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
