/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type UpdateProductRequestBody = {
    data: components.ProductUpdate;
};

export type UpdateProductRequest = {
    /**
     * The unique identifier of a product.
     */
    productUuid: string;
    requestBody?: UpdateProductRequestBody | undefined;
};

/**
 * Success. The product details are updated.
 */
export type UpdateProductResponseBody = {
    data?: components.Product | undefined;
};

export type UpdateProductResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success. The product details are updated.
     */
    object?: UpdateProductResponseBody | undefined;
};

/** @internal */
export namespace UpdateProductRequestBody$ {
    export type Inbound = {
        data: components.ProductUpdate$.Inbound;
    };

    export const inboundSchema: z.ZodType<UpdateProductRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.ProductUpdate$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: components.ProductUpdate$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateProductRequestBody> = z
        .object({
            data: components.ProductUpdate$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace UpdateProductRequest$ {
    export type Inbound = {
        product_uuid: string;
        RequestBody?: UpdateProductRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateProductRequest, z.ZodTypeDef, Inbound> = z
        .object({
            product_uuid: z.string(),
            RequestBody: z.lazy(() => UpdateProductRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                productUuid: v.product_uuid,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        product_uuid: string;
        RequestBody?: UpdateProductRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateProductRequest> = z
        .object({
            productUuid: z.string(),
            requestBody: z.lazy(() => UpdateProductRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                product_uuid: v.productUuid,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace UpdateProductResponseBody$ {
    export type Inbound = {
        data?: components.Product$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateProductResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.Product$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: components.Product$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateProductResponseBody> = z
        .object({
            data: components.Product$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });
}

/** @internal */
export namespace UpdateProductResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: UpdateProductResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateProductResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => UpdateProductResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: UpdateProductResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateProductResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => UpdateProductResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
