/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { JobMeta, JobMeta$ } from "./jobmeta";
import { JobResponseAttributes, JobResponseAttributes$ } from "./jobresponseattributes";
import { Relationship, Relationship$ } from "./relationship";
import { SubscriptionJobType, SubscriptionJobType$ } from "./subscriptionjobtype";
import { z } from "zod";

export type Job = {
    /**
     * The unique identifier.
     */
    id?: string | undefined;
    type?: SubscriptionJobType | undefined;
    attributes: JobResponseAttributes;
    /**
     * Relationships are established between different subscription entities. For example, a product and a plan are related to an offering, as both are attached to it.
     */
    relationships?: Record<string, Relationship> | undefined;
    meta: JobMeta;
};

/** @internal */
export namespace Job$ {
    export type Inbound = {
        id?: string | undefined;
        type?: SubscriptionJobType | undefined;
        attributes: JobResponseAttributes$.Inbound;
        relationships?: Record<string, Relationship$.Inbound> | undefined;
        meta: JobMeta$.Inbound;
    };

    export const inboundSchema: z.ZodType<Job, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            type: SubscriptionJobType$.default(SubscriptionJobType.SubscriptionJob),
            attributes: JobResponseAttributes$.inboundSchema,
            relationships: z.record(Relationship$.inboundSchema).optional(),
            meta: JobMeta$.inboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                type: v.type,
                attributes: v.attributes,
                ...(v.relationships === undefined ? null : { relationships: v.relationships }),
                meta: v.meta,
            };
        });

    export type Outbound = {
        id?: string | undefined;
        type: SubscriptionJobType;
        attributes: JobResponseAttributes$.Outbound;
        relationships?: Record<string, Relationship$.Outbound> | undefined;
        meta: JobMeta$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Job> = z
        .object({
            id: z.string().optional(),
            type: SubscriptionJobType$.default(SubscriptionJobType.SubscriptionJob),
            attributes: JobResponseAttributes$.outboundSchema,
            relationships: z.record(Relationship$.outboundSchema).optional(),
            meta: JobMeta$.outboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                type: v.type,
                attributes: v.attributes,
                ...(v.relationships === undefined ? null : { relationships: v.relationships }),
                meta: v.meta,
            };
        });
}
