/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { JobType, JobType$ } from "./jobtype";
import { z } from "zod";

/**
 * The status of job.
 */
export enum JobResponseAttributesStatus {
    Pending = "pending",
    Started = "started",
    Success = "success",
    Failed = "failed",
}

export type JobResponseAttributes = {
    /**
     * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
     */
    externalRef?: string | undefined;
    /**
     * The type of job. One of the following:
     *
     * @remarks
     *  - `billing_run` - a billing run job.
     *  - `payment_run` - a payment run job.
     *
     */
    jobType: JobType;
    /**
     * The status of job.
     */
    status: JobResponseAttributesStatus;
    /**
     * The date and time a resource was updated.
     */
    updatedAt: string;
    /**
     * The date and time a resource was created.
     */
    createdAt: string;
    /**
     * The date and time a resource was cancelled.
     */
    canceledAt: string | null;
};

/** @internal */
export const JobResponseAttributesStatus$ = z.nativeEnum(JobResponseAttributesStatus);

/** @internal */
export namespace JobResponseAttributes$ {
    export type Inbound = {
        external_ref?: string | undefined;
        job_type: JobType;
        status: JobResponseAttributesStatus;
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const inboundSchema: z.ZodType<JobResponseAttributes, z.ZodTypeDef, Inbound> = z
        .object({
            external_ref: z.string().optional(),
            job_type: JobType$,
            status: JobResponseAttributesStatus$,
            updated_at: z.string(),
            created_at: z.string(),
            canceled_at: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                ...(v.external_ref === undefined ? null : { externalRef: v.external_ref }),
                jobType: v.job_type,
                status: v.status,
                updatedAt: v.updated_at,
                createdAt: v.created_at,
                canceledAt: v.canceled_at,
            };
        });

    export type Outbound = {
        external_ref?: string | undefined;
        job_type: JobType;
        status: JobResponseAttributesStatus;
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, JobResponseAttributes> = z
        .object({
            externalRef: z.string().optional(),
            jobType: JobType$,
            status: JobResponseAttributesStatus$,
            updatedAt: z.string(),
            createdAt: z.string(),
            canceledAt: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                ...(v.externalRef === undefined ? null : { external_ref: v.externalRef }),
                job_type: v.jobType,
                status: v.status,
                updated_at: v.updatedAt,
                created_at: v.createdAt,
                canceled_at: v.canceledAt,
            };
        });
}
