/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * The type of job. One of the following:
 *
 * @remarks
 *  - `billing_run` - a billing run job.
 *  - `payment_run` - a payment run job.
 *
 */
export enum JobType {
    BillingRun = "billing-run",
    PaymentRun = "payment-run",
}

/** @internal */
export const JobType$ = z.nativeEnum(JobType);
