/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type JobTimestamps = {
    /**
     * The date and time a resource was updated.
     */
    updatedAt: string;
    /**
     * The date and time a resource was created.
     */
    createdAt: string;
    /**
     * The date and time a resource was cancelled.
     */
    canceledAt: string | null;
    startedAt?: string | undefined;
    finishedAt?: string | undefined;
};

/** @internal */
export namespace JobTimestamps$ {
    export type Inbound = {
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
        started_at?: string | undefined;
        finished_at?: string | undefined;
    };

    export const inboundSchema: z.ZodType<JobTimestamps, z.ZodTypeDef, Inbound> = z
        .object({
            updated_at: z.string(),
            created_at: z.string(),
            canceled_at: z.nullable(z.string()),
            started_at: z.string().optional(),
            finished_at: z.string().optional(),
        })
        .transform((v) => {
            return {
                updatedAt: v.updated_at,
                createdAt: v.created_at,
                canceledAt: v.canceled_at,
                ...(v.started_at === undefined ? null : { startedAt: v.started_at }),
                ...(v.finished_at === undefined ? null : { finishedAt: v.finished_at }),
            };
        });

    export type Outbound = {
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
        started_at?: string | undefined;
        finished_at?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, JobTimestamps> = z
        .object({
            updatedAt: z.string(),
            createdAt: z.string(),
            canceledAt: z.nullable(z.string()),
            startedAt: z.string().optional(),
            finishedAt: z.string().optional(),
        })
        .transform((v) => {
            return {
                updated_at: v.updatedAt,
                created_at: v.createdAt,
                canceled_at: v.canceledAt,
                ...(v.startedAt === undefined ? null : { started_at: v.startedAt }),
                ...(v.finishedAt === undefined ? null : { finished_at: v.finishedAt }),
            };
        });
}
