/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * A unit of time, either days or months.
 */
export enum NullablePriceUnitsUnit {
    Day = "day",
    Month = "month",
}

/**
 * The timeframe during which the product price is applicable. For example, for a streaming service, the price is $12.99 and the `unit` is `months` and the `amount` is `1`. In other words, the streaming service is available for $12.99 a month. You may want to specify a unit price if you have many products that all have different prices. Rather than having to create separate plans for each product, you can specify the timeframe during which the product price is applicable and then create one plan that determines the billing frequency for those products.
 */
export type NullablePriceUnits = {
    /**
     * A unit of time, either days or months.
     */
    unit: NullablePriceUnitsUnit;
    /**
     * The number of days or months the period covers.
     */
    amount: number;
};

/** @internal */
export const NullablePriceUnitsUnit$ = z.nativeEnum(NullablePriceUnitsUnit);

/** @internal */
export namespace NullablePriceUnits$ {
    export type Inbound = {
        unit: NullablePriceUnitsUnit;
        amount: number;
    };

    export const inboundSchema: z.ZodType<NullablePriceUnits, z.ZodTypeDef, Inbound> = z
        .object({
            unit: NullablePriceUnitsUnit$,
            amount: z.number().int(),
        })
        .transform((v) => {
            return {
                unit: v.unit,
                amount: v.amount,
            };
        });

    export type Outbound = {
        unit: NullablePriceUnitsUnit;
        amount: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NullablePriceUnits> = z
        .object({
            unit: NullablePriceUnitsUnit$,
            amount: z.number().int(),
        })
        .transform((v) => {
            return {
                unit: v.unit,
                amount: v.amount,
            };
        });
}
