/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * A list of product IDs to attach to the offering. See [**List Products**](#tag/Products/operation/ListProducts).
 */
export type OfferingProductAttach = {
    products: Array<string>;
};

/** @internal */
export namespace OfferingProductAttach$ {
    export type Inbound = {
        products: Array<string>;
    };

    export const inboundSchema: z.ZodType<OfferingProductAttach, z.ZodTypeDef, Inbound> = z
        .object({
            products: z.array(z.string()),
        })
        .transform((v) => {
            return {
                products: v.products,
            };
        });

    export type Outbound = {
        products: Array<string>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, OfferingProductAttach> = z
        .object({
            products: z.array(z.string()),
        })
        .transform((v) => {
            return {
                products: v.products,
            };
        });
}
