/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { PlanUpdateAttributes, PlanUpdateAttributes$ } from "./planupdateattributes";
import { SubscriptionPlanType, SubscriptionPlanType$ } from "./subscriptionplantype";
import { z } from "zod";

export type PlanUpdate = {
    /**
     * The unique identifier.
     */
    id: string;
    type?: SubscriptionPlanType | undefined;
    attributes: PlanUpdateAttributes;
};

/** @internal */
export namespace PlanUpdate$ {
    export type Inbound = {
        id: string;
        type?: SubscriptionPlanType | undefined;
        attributes: PlanUpdateAttributes$.Inbound;
    };

    export const inboundSchema: z.ZodType<PlanUpdate, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
            type: SubscriptionPlanType$.default(SubscriptionPlanType.SubscriptionPlan),
            attributes: PlanUpdateAttributes$.inboundSchema,
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                attributes: v.attributes,
            };
        });

    export type Outbound = {
        id: string;
        type: SubscriptionPlanType;
        attributes: PlanUpdateAttributes$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PlanUpdate> = z
        .object({
            id: z.string(),
            type: SubscriptionPlanType$.default(SubscriptionPlanType.SubscriptionPlan),
            attributes: PlanUpdateAttributes$.outboundSchema,
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                attributes: v.attributes,
            };
        });
}
