/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { DisplayPrice, DisplayPrice$ } from "./displayprice";
import { Timestamps, Timestamps$ } from "./timestamps";
import { z } from "zod";

export type ProductMeta = {
    displayPrice?: DisplayPrice | undefined;
    /**
     * The owner of a resource, either `store` or `organization`.
     */
    owner: string;
    timestamps: Timestamps;
};

/** @internal */
export namespace ProductMeta$ {
    export type Inbound = {
        display_price?: DisplayPrice$.Inbound | undefined;
        owner: string;
        timestamps: Timestamps$.Inbound;
    };

    export const inboundSchema: z.ZodType<ProductMeta, z.ZodTypeDef, Inbound> = z
        .object({
            display_price: DisplayPrice$.inboundSchema.optional(),
            owner: z.string(),
            timestamps: Timestamps$.inboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.display_price === undefined ? null : { displayPrice: v.display_price }),
                owner: v.owner,
                timestamps: v.timestamps,
            };
        });

    export type Outbound = {
        display_price?: DisplayPrice$.Outbound | undefined;
        owner: string;
        timestamps: Timestamps$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProductMeta> = z
        .object({
            displayPrice: DisplayPrice$.outboundSchema.optional(),
            owner: z.string(),
            timestamps: Timestamps$.outboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.displayPrice === undefined ? null : { display_price: v.displayPrice }),
                owner: v.owner,
                timestamps: v.timestamps,
            };
        });
}
