/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NullablePrice, NullablePrice$ } from "./nullableprice";
import { NullablePriceUnits, NullablePriceUnits$ } from "./nullablepriceunits";
import { z } from "zod";

export type ProductUpdateAttributes = {
    /**
     * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
     */
    externalRef?: string | null | undefined;
    /**
     * The name of the product.
     */
    name?: string | undefined;
    /**
     * The product or service description to display to customers.
     */
    description?: string | null | undefined;
    /**
     * A stock keeping unit for the product, if appropriate.
     */
    sku?: string | null | undefined;
    /**
     * A URL from which an image or file for the product can be fetched. You can either upload your images and files to Commerce using the Commerce Files API or you can use your own content delivery network. If you are using the Commerce Files API, use [**Create a File**](https://elasticpath.dev/docs/pxm/products/product-assets/create-a-file) to upload your file and return an HREF link in the response. An extensive range of [**media and file extensions**](https://elasticpath.dev/docs/pxm/products/product-assets/files-overview) are supported.
     */
    mainImage?: string | null | undefined;
    price?: Record<string, NullablePrice> | null | undefined;
    /**
     * The timeframe during which the product price is applicable. For example, for a streaming service, the price is $12.99 and the `unit` is `months` and the `amount` is `1`. In other words, the streaming service is available for $12.99 a month. You may want to specify a unit price if you have many products that all have different prices. Rather than having to create separate plans for each product, you can specify the timeframe during which the product price is applicable and then create one plan that determines the billing frequency for those products.
     */
    priceUnits?: NullablePriceUnits | null | undefined;
};

/** @internal */
export namespace ProductUpdateAttributes$ {
    export type Inbound = {
        external_ref?: string | null | undefined;
        name?: string | undefined;
        description?: string | null | undefined;
        sku?: string | null | undefined;
        main_image?: string | null | undefined;
        price?: Record<string, NullablePrice$.Inbound> | null | undefined;
        price_units?: NullablePriceUnits$.Inbound | null | undefined;
    };

    export const inboundSchema: z.ZodType<ProductUpdateAttributes, z.ZodTypeDef, Inbound> = z
        .object({
            external_ref: z.nullable(z.string()).optional(),
            name: z.string().optional(),
            description: z.nullable(z.string()).optional(),
            sku: z.nullable(z.string()).optional(),
            main_image: z.nullable(z.string()).optional(),
            price: z.nullable(z.record(NullablePrice$.inboundSchema)).optional(),
            price_units: z.nullable(NullablePriceUnits$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.external_ref === undefined ? null : { externalRef: v.external_ref }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.main_image === undefined ? null : { mainImage: v.main_image }),
                ...(v.price === undefined ? null : { price: v.price }),
                ...(v.price_units === undefined ? null : { priceUnits: v.price_units }),
            };
        });

    export type Outbound = {
        external_ref?: string | null | undefined;
        name?: string | undefined;
        description?: string | null | undefined;
        sku?: string | null | undefined;
        main_image?: string | null | undefined;
        price?: Record<string, NullablePrice$.Outbound> | null | undefined;
        price_units?: NullablePriceUnits$.Outbound | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProductUpdateAttributes> = z
        .object({
            externalRef: z.nullable(z.string()).optional(),
            name: z.string().optional(),
            description: z.nullable(z.string()).optional(),
            sku: z.nullable(z.string()).optional(),
            mainImage: z.nullable(z.string()).optional(),
            price: z.nullable(z.record(NullablePrice$.outboundSchema)).optional(),
            priceUnits: z.nullable(NullablePriceUnits$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.externalRef === undefined ? null : { external_ref: v.externalRef }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.mainImage === undefined ? null : { main_image: v.mainImage }),
                ...(v.price === undefined ? null : { price: v.price }),
                ...(v.priceUnits === undefined ? null : { price_units: v.priceUnits }),
            };
        });
}
