/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Timestamps, Timestamps$ } from "./timestamps";
import { z } from "zod";

export type ScheduleMeta = {
    scheduledFor?: Date | undefined;
    /**
     * The owner of a resource, either `store` or `organization`.
     */
    owner: string;
    timestamps: Timestamps;
};

/** @internal */
export namespace ScheduleMeta$ {
    export type Inbound = {
        scheduled_for?: string | undefined;
        owner: string;
        timestamps: Timestamps$.Inbound;
    };

    export const inboundSchema: z.ZodType<ScheduleMeta, z.ZodTypeDef, Inbound> = z
        .object({
            scheduled_for: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            owner: z.string(),
            timestamps: Timestamps$.inboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.scheduled_for === undefined ? null : { scheduledFor: v.scheduled_for }),
                owner: v.owner,
                timestamps: v.timestamps,
            };
        });

    export type Outbound = {
        scheduled_for?: string | undefined;
        owner: string;
        timestamps: Timestamps$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ScheduleMeta> = z
        .object({
            scheduledFor: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            owner: z.string(),
            timestamps: Timestamps$.outboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.scheduledFor === undefined ? null : { scheduled_for: v.scheduledFor }),
                owner: v.owner,
                timestamps: v.timestamps,
            };
        });
}
