/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { JobType, JobType$ } from "./jobtype";
import { z } from "zod";

export type ScheduleJob = {
    /**
     * The type of job. One of the following:
     *
     * @remarks
     *  - `billing_run` - a billing run job.
     *  - `payment_run` - a payment run job.
     *
     */
    jobType: JobType;
};

/** @internal */
export namespace ScheduleJob$ {
    export type Inbound = {
        job_type: JobType;
    };

    export const inboundSchema: z.ZodType<ScheduleJob, z.ZodTypeDef, Inbound> = z
        .object({
            job_type: JobType$,
        })
        .transform((v) => {
            return {
                jobType: v.job_type,
            };
        });

    export type Outbound = {
        job_type: JobType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ScheduleJob> = z
        .object({
            jobType: JobType$,
        })
        .transform((v) => {
            return {
                job_type: v.jobType,
            };
        });
}
