/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ScheduleJob, ScheduleJob$ } from "./schedulejob";
import { z } from "zod";

export type ScheduleResponseAttributes = {
    /**
     * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
     */
    externalRef?: string | undefined;
    /**
     * The name of the schedule.
     */
    name?: string | undefined;
    /**
     * A cron-style specification of when the jobs should be created. See [**Schedules**](#tag/Schedules).
     */
    specification: string;
    /**
     * The location of the time zone that the schedule operates in. Subscriptions runs on Coordinated Universal Time (UTC) time and conforms to [**RFC 3339**](https://www.rfc-editor.org/rfc/rfc3339).
     */
    location: string;
    job: ScheduleJob;
    /**
     * The date and time a resource was updated.
     */
    updatedAt: string;
    /**
     * The date and time a resource was created.
     */
    createdAt: string;
    /**
     * The date and time a resource was cancelled.
     */
    canceledAt: string | null;
};

/** @internal */
export namespace ScheduleResponseAttributes$ {
    export type Inbound = {
        external_ref?: string | undefined;
        name?: string | undefined;
        specification: string;
        location: string;
        job: ScheduleJob$.Inbound;
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const inboundSchema: z.ZodType<ScheduleResponseAttributes, z.ZodTypeDef, Inbound> = z
        .object({
            external_ref: z.string().optional(),
            name: z.string().optional(),
            specification: z.string(),
            location: z.string(),
            job: ScheduleJob$.inboundSchema,
            updated_at: z.string(),
            created_at: z.string(),
            canceled_at: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                ...(v.external_ref === undefined ? null : { externalRef: v.external_ref }),
                ...(v.name === undefined ? null : { name: v.name }),
                specification: v.specification,
                location: v.location,
                job: v.job,
                updatedAt: v.updated_at,
                createdAt: v.created_at,
                canceledAt: v.canceled_at,
            };
        });

    export type Outbound = {
        external_ref?: string | undefined;
        name?: string | undefined;
        specification: string;
        location: string;
        job: ScheduleJob$.Outbound;
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ScheduleResponseAttributes> = z
        .object({
            externalRef: z.string().optional(),
            name: z.string().optional(),
            specification: z.string(),
            location: z.string(),
            job: ScheduleJob$.outboundSchema,
            updatedAt: z.string(),
            createdAt: z.string(),
            canceledAt: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                ...(v.externalRef === undefined ? null : { external_ref: v.externalRef }),
                ...(v.name === undefined ? null : { name: v.name }),
                specification: v.specification,
                location: v.location,
                job: v.job,
                updated_at: v.updatedAt,
                created_at: v.createdAt,
                canceled_at: v.canceledAt,
            };
        });
}
