/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ScheduleJob, ScheduleJob$ } from "./schedulejob";
import { z } from "zod";

export type ScheduleAttributes = {
    /**
     * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
     */
    externalRef?: string | undefined;
    /**
     * The name of the schedule.
     */
    name?: string | undefined;
    /**
     * A cron-style specification of when the jobs should be created. See [**Schedules**](#tag/Schedules).
     */
    specification: string;
    /**
     * The location of the time zone that the schedule operates in. Subscriptions runs on Coordinated Universal Time (UTC) time and conforms to [**RFC 3339**](https://www.rfc-editor.org/rfc/rfc3339).
     */
    location: string;
    job: ScheduleJob;
};

/** @internal */
export namespace ScheduleAttributes$ {
    export type Inbound = {
        external_ref?: string | undefined;
        name?: string | undefined;
        specification: string;
        location: string;
        job: ScheduleJob$.Inbound;
    };

    export const inboundSchema: z.ZodType<ScheduleAttributes, z.ZodTypeDef, Inbound> = z
        .object({
            external_ref: z.string().optional(),
            name: z.string().optional(),
            specification: z.string(),
            location: z.string(),
            job: ScheduleJob$.inboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.external_ref === undefined ? null : { externalRef: v.external_ref }),
                ...(v.name === undefined ? null : { name: v.name }),
                specification: v.specification,
                location: v.location,
                job: v.job,
            };
        });

    export type Outbound = {
        external_ref?: string | undefined;
        name?: string | undefined;
        specification: string;
        location: string;
        job: ScheduleJob$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ScheduleAttributes> = z
        .object({
            externalRef: z.string().optional(),
            name: z.string().optional(),
            specification: z.string(),
            location: z.string(),
            job: ScheduleJob$.outboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.externalRef === undefined ? null : { external_ref: v.externalRef }),
                ...(v.name === undefined ? null : { name: v.name }),
                specification: v.specification,
                location: v.location,
                job: v.job,
            };
        });
}
