/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * A price in a single currency.
 */
export type SingleCurrencyPrice = {
    /**
     * The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) in uppercase, associated with a price.
     */
    currency: string;
    /**
     * The value as a whole number of the currency's smallest subdivision.
     */
    amount: number;
    /**
     * Whether the amount includes any taxes.
     */
    includesTax?: boolean | undefined;
};

/** @internal */
export namespace SingleCurrencyPrice$ {
    export type Inbound = {
        currency: string;
        amount: number;
        includes_tax?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<SingleCurrencyPrice, z.ZodTypeDef, Inbound> = z
        .object({
            currency: z.string(),
            amount: z.number().int(),
            includes_tax: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                currency: v.currency,
                amount: v.amount,
                ...(v.includes_tax === undefined ? null : { includesTax: v.includes_tax }),
            };
        });

    export type Outbound = {
        currency: string;
        amount: number;
        includes_tax?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SingleCurrencyPrice> = z
        .object({
            currency: z.string(),
            amount: z.number().int(),
            includesTax: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                currency: v.currency,
                amount: v.amount,
                ...(v.includesTax === undefined ? null : { includes_tax: v.includesTax }),
            };
        });
}
