/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * The status of a subscription, either `active` or `inactive`.
 */
export enum Status {
    Active = "active",
    Inactive = "inactive",
}

/** @internal */
export const Status$ = z.nativeEnum(Status);
