/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * This represents the type of resource object being returned. Always `subscription_invoice`.
 */
export enum SubscriptionInvoiceType {
    SubscriptionInvoice = "subscription_invoice",
}

/** @internal */
export const SubscriptionInvoiceType$ = z.nativeEnum(SubscriptionInvoiceType);
