/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type SubscriberUpdateAttributes = {
    /**
     * The name of the subscriber.
     */
    name?: string | undefined;
    /**
     * The email of the subscriber.
     */
    email?: string | undefined;
};

/** @internal */
export namespace SubscriberUpdateAttributes$ {
    export type Inbound = {
        name?: string | undefined;
        email?: string | undefined;
    };

    export const inboundSchema: z.ZodType<SubscriberUpdateAttributes, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string().optional(),
            email: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.email === undefined ? null : { email: v.email }),
            };
        });

    export type Outbound = {
        name?: string | undefined;
        email?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SubscriberUpdateAttributes> = z
        .object({
            name: z.string().optional(),
            email: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.email === undefined ? null : { email: v.email }),
            };
        });
}
