/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * This represents the type of resource object being returned. Always `subscription_invoice_payment`.
 */
export enum SubscriptionInvoicePaymentType {
    SubscriptionInvoicePayment = "subscription_invoice_payment",
}

/** @internal */
export const SubscriptionInvoicePaymentType$ = z.nativeEnum(SubscriptionInvoicePaymentType);
