/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionJobType {
    SubscriptionJob = "subscription_job",
}

/** @internal */
export const SubscriptionJobType$ = z.nativeEnum(SubscriptionJobType);
