/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionPlanType {
    SubscriptionPlan = "subscription_plan",
}

/** @internal */
export const SubscriptionPlanType$ = z.nativeEnum(SubscriptionPlanType);
