/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionScheduleType {
    SubscriptionSchedule = "subscription_schedule",
}

/** @internal */
export const SubscriptionScheduleType$ = z.nativeEnum(SubscriptionScheduleType);
