/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionOfferingPlanType {
    SubscriptionOfferingPlan = "subscription_offering_plan",
}

/** @internal */
export const SubscriptionOfferingPlanType$ = z.nativeEnum(SubscriptionOfferingPlanType);
