/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionOfferingType {
    SubscriptionOffering = "subscription_offering",
}

/** @internal */
export const SubscriptionOfferingType$ = z.nativeEnum(SubscriptionOfferingType);
