/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionProductType {
    SubscriptionProduct = "subscription_product",
}

/** @internal */
export const SubscriptionProductType$ = z.nativeEnum(SubscriptionProductType);
