/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionSubscriberType {
    SubscriptionSubscriber = "subscription_subscriber",
}

/** @internal */
export const SubscriptionSubscriberType$ = z.nativeEnum(SubscriptionSubscriberType);
