/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionType {
    Subscription = "subscription",
}

/** @internal */
export const SubscriptionType$ = z.nativeEnum(SubscriptionType);
