/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Timestamps = {
    /**
     * The date and time a resource was updated.
     */
    updatedAt: string;
    /**
     * The date and time a resource was created.
     */
    createdAt: string;
    /**
     * The date and time a resource was cancelled.
     */
    canceledAt: string | null;
};

/** @internal */
export namespace Timestamps$ {
    export type Inbound = {
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const inboundSchema: z.ZodType<Timestamps, z.ZodTypeDef, Inbound> = z
        .object({
            updated_at: z.string(),
            created_at: z.string(),
            canceled_at: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                updatedAt: v.updated_at,
                createdAt: v.created_at,
                canceledAt: v.canceled_at,
            };
        });

    export type Outbound = {
        updated_at: string;
        created_at: string;
        canceled_at: string | null;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Timestamps> = z
        .object({
            updatedAt: z.string(),
            createdAt: z.string(),
            canceledAt: z.nullable(z.string()),
        })
        .transform((v) => {
            return {
                updated_at: v.updatedAt,
                created_at: v.createdAt,
                canceled_at: v.canceledAt,
            };
        });
}
