/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { HTTPClient } from "./http";
import { RetryConfig } from "./retries";
import { pathToFunc } from "./url";

/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = [
    /**
     * Integration cluster
     */
    "https://epcc-integration.global.ssl.fastly.net/v2",
    /**
     * Staging cluster
     */
    "https://api.epcc-staging.epcloudops.com/v2",
    /**
     * EU west cluster
     */
    "https://api.moltin.com/v2",
    /**
     * US east cluster
     */
    "https://useast.api.elasticpath.com/v2",
] as const;

export type SDKOptions = {
    bearerToken?: string | (() => Promise<string>);

    httpClient?: HTTPClient;
    /**
     * Allows overriding the default server used by the SDK
     */
    serverIdx?: number;
    /**
     * Allows overriding the default server URL used by the SDK
     */
    serverURL?: string;
    /**
     * Allows overriding the default retry config used by the SDK
     */
    retryConfig?: RetryConfig;
};

export function serverURLFromOptions(options: SDKOptions): URL | null {
    let serverURL = options.serverURL;

    const params: Record<string, string> = {};
    const serverIdx = options.serverIdx ?? 0;

    if (!serverURL) {
        serverURL = ServerList[serverIdx] || "";
    }

    const u = pathToFunc(serverURL)(params);
    return new URL(u);
}

export const SDK_METADATA = Object.freeze({
    language: "typescript",
    openapiDocVersion: "1.0.0",
    sdkVersion: "0.0.4",
    genVersion: "2.259.1",
    userAgent: "speakeasy-sdk/typescript 0.0.4 2.259.1 1.0.0 service-subscriptions-sdk",
});
